# Write your MySQL query statement below
SELECT * 
FROM (
   SELECT
       DISTINCT REQUESTER_ID AS ID,
       (SELECT COUNT(*) 
        FROM REQUESTACCEPTED 
        WHERE ID=REQUESTER_ID OR ID=ACCEPTER_ID) AS NUM
   FROM REQUESTACCEPTED
   UNION
   SELECT
       DISTINCT ACCEPTER_ID AS ID,
       (SELECT COUNT(*) 
        FROM REQUESTACCEPTED 
        WHERE ID=REQUESTER_ID OR ID=ACCEPTER_ID) AS NUM
   FROM REQUESTACCEPTED
) A
ORDER BY NUM DESC
LIMIT 1