# Write your MySQL query statement below
SELECT * 
FROM (
   SELECT
       DISTINCT REQUESTER_ID as ID,
       (SELECT COUNT(*) 
        FROM REQUESTACCEPTED 
        WHERE ID = REQUESTER_ID or ID = ACCEPTER_ID) as NUM
   FROM REQUESTACCEPTED
   UNION
   SELECT
       DISTINCT ACCEPTER_ID as ID,
       (SELECT COUNT(*) 
        FROM REQUESTACCEPTED 
        WHERE ID = REQUESTER_ID or ID = ACCEPTER_ID) as NUM
   FROM REQUESTACCEPTED
) A
ORDER BY NUM DESC
LIMIT 1