-- 코드를 입력하세요
SELECT MONTH(START_DATE) as MONTH, CAR_ID, COUNT(CAR_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE,'%Y-%m') between '2022-08' and '2022-10'
    and CAR_ID in 
        (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE DATE_FORMAT(START_DATE,'%Y-%m') between '2022-08' and '2022-10'
        group by 1
        HAVING COUNT(CAR_ID) >= 5) 
    GROUP BY 1,2
    ORDER BY 1,2 desc