-- 코드를 작성해주세요
SELECT 
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, 
    PRODUCT_ID, 
    IFNULL(USER_ID, NULL) as USER_ID, 
    SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 3
UNION ALL
SELECT 
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE,
    PRODUCT_ID,
    NULL, 
    SALES_AMOUNT 
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 3
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
