-- 코드를 입력하세요
SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    FLOOR(C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)) as FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY RH 
    on C.CAR_ID = RH.CAR_ID 
    and RH.START_DATE <= '2022-11-30' 
    and RH.END_DATE >= '2022-11-01'
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP 
    on C.CAR_TYPE = DP.CAR_TYPE 
    and DP.DURATION_TYPE = '30일 이상'
WHERE 
    C.CAR_TYPE in ('세단', 'SUV')
    AND RH.HISTORY_ID is NULL  
HAVING 
    FEE >= 500000 and FEE < 2000000
ORDER BY 
    FEE DESC, 
    C.CAR_TYPE ASC, 
    C.CAR_ID DESC