-- 코드를 작성해주세요
WITH T1 as (
    SELECT 
        ID,
        FISH_TYPE,
        CASE WHEN LENGTH is NULL THEN 10 
             ELSE LENGTH END as LENGTH
    FROM FISH_INFO
)
SELECT 
    COUNT(ID) as FISH_COUNT, 
    MAX(LENGTH) as MAX_LENGTH, 
    FISH_TYPE
FROM T1
GROUP BY 3
HAVING AVG(LENGTH) >= 33
ORDER BY 3 ASC