-- 코드를 작성해주세요
SELECT 
    FOOD_TYPE, 
    REST_ID, 
    REST_NAME, 
    FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) in (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY 1
)
ORDER BY 1 DESC