-- 코드를 입력하세요
SELECT
    i.REST_ID,
    i.REST_NAME,
    i.FOOD_TYPE,
    i.FAVORITES,
    i.ADDRESS,
    ROUND(AVG(REVIEW_SCORE), 2) as SCORE
FROM REST_INFO i
JOIN REST_REVIEW r on r.REST_ID = i.REST_ID
WHERE LEFT(ADDRESS, 2) = '서울'
GROUP BY 1
ORDER BY 6 DESC, 4 DESC
