-- 코드를 작성해주세요
SELECT QUARTER,
    COUNT(QUARTER) as ECOLI_COUNT
FROM (
     SELECT CASE WHEN MONTH(DIFFERENTIATION_DATE) between 1 and 3 THEN '1Q'
                 WHEN MONTH(DIFFERENTIATION_DATE) between 4 and 6 THEN '2Q'
                 WHEN MONTH(DIFFERENTIATION_DATE) between 7 and 9 THEN '3Q'
                 WHEN MONTH(DIFFERENTIATION_DATE) between 10 and 12 THEN '4Q'
                 END as QUARTER
     FROM ECOLI_DATA
     ) as T1
GROUP BY 1
ORDER BY 1