-- 코드를 입력하세요
SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
    , ROUND(AVG(REVIEW_SCORE), 2) as SCORE
FROM REST_INFO i
JOIN REST_REVIEW r on i.REST_ID = r.REST_ID
WHERE i.ADDRESS like "서울%" and r.REVIEW_SCORE is not NULL
GROUP BY i.REST_ID
ORDER BY SCORE DESC, i.FAVORITES DESC