-- 코드를 입력하세요
WITH USER_21 AS (
    SELECT *
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)
SELECT 
    YEAR(o.SALES_DATE) as YEAR,
    MONTH(o.SALES_DATE) as MONTH,
    COUNT(DISTINCT o.USER_ID) as PURCHASED_USERS,
    ROUND(COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(*) FROM USER_21), 1) as PURCHASED_RATIO
FROM USER_21 u
INNER JOIN ONLINE_SALE o on u.USER_ID = o.USER_ID
GROUP BY 1, 2
ORDER BY 1, 2