-- 코드를 입력하세요
SELECT
    o.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(o.AMOUNT) * p.PRICE as TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o on o.PRODUCT_ID = p.PRODUCT_ID
WHERE DATE_FORMAT(o.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY 1
ORDER BY 3 DESC, 1 ASC