-- 코드를 입력하세요
SELECT 
    A.HISTORY_ID, 
    ROUND(A.DAILY_FEE * (1 - COALESCE(B.DISCOUNT_RATE / 100,0)) * A.DURATION, 0) as FEE
FROM (SELECT 
        A.HISTORY_ID, 
        A.CAR_ID,
        A.START_DATE, 
        A.END_DATE, 
        DATEDIFF(A.END_DATE, A.START_DATE) + 1 as DURATION,B.CAR_TYPE, 
        B.DAILY_FEE,
        CASE WHEN DATEDIFF(A.END_DATE, A.START_DATE)+1 >= 90 THEN '90일 이상'
             WHEN DATEDIFF(A.END_DATE, A.START_DATE)+1 >= 30 THEN '30일 이상'
             WHEN DATEDIFF(A.END_DATE, A.START_DATE)+1 >= 7 THEN '7일 이상'
             ELSE '할인 없음' END as 'DURATION_TYPE'
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
      LEFT JOIN CAR_RENTAL_COMPANY_CAR B on A.CAR_ID = B.CAR_ID
      WHERE B.CAR_TYPE = '트럭'
) as A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B on (A.DURATION_TYPE = B.DURATION_TYPE) and (A.CAR_TYPE = B.CAR_TYPE)
ORDER BY 2 DESC, 1 DESC