-- 코드를 입력하세요
SELECT 
    HOUR, 
    COUNT(ANIMAL_ID) as COUNT
FROM (
    SELECT (ROW_NUMBER() OVER () - 1) as HOUR
    FROM INFORMATION_SCHEMA.TABLES
    LIMIT 24
) AS T1 
LEFT JOIN ANIMAL_OUTS on HOUR = HOUR(DATETIME)
GROUP BY 1
ORDER BY 1