-- 코드를 입력하세요
SELECT
    u.USER_ID,
    u.NICKNAME,
    SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_USER u on u.USER_ID = b.WRITER_ID
WHERE STATUS = 'DONE'
GROUP BY 1
HAVING SUM(PRICE) >= 700000
ORDER BY 3