-- 코드를 작성해주세요
SELECT
    e.EMP_NO,
    e.EMP_NAME,
    CASE WHEN AVG(g.SCORE) >= 96 THEN 'S' 
         WHEN AVG(g.SCORE) >= 90 THEN 'A'
         WHEN AVG(g.SCORE) >= 80 THEN 'B'
         ELSE 'C' END as GRADE,
    CASE WHEN AVG(g.SCORE) >= 96 THEN SAL * 0.2
         WHEN AVG(g.SCORE) >= 90 THEN SAL * 0.15
         WHEN AVG(g.SCORE) >= 80 THEN SAL * 0.1
         ELSE 0 END as BONUS
FROM HR_EMPLOYEES e
JOIN HR_DEPARTMENT d on d.DEPT_ID = e.DEPT_ID
JOIN HR_GRADE g on g.EMP_NO = e.EMP_NO
GROUP BY 1
ORDER BY 1 ASC