-- 코드를 작성해주세요
SELECT 
    temp.ITEM_ID, 
    ITEM_NAME, 
    RARITY
FROM (
    SELECT 
        t.ITEM_ID
    FROM ITEM_INFO i
    LEFT JOIN ITEM_TREE t ON i.ITEM_ID = t.PARENT_ITEM_ID
    WHERE RARITY = 'RARE' AND t.ITEM_ID IS NOT NULL) as temp 
LEFT JOIN ITEM_INFO AS i2 ON temp.ITEM_ID = i2.ITEM_ID
ORDER BY 1 DESC
