-- 코드를 입력하세요
SELECT
    DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h on h.CAR_ID = c.CAR_ID
WHERE c.CAR_TYPE = '세단' and MONTH(h.START_DATE) = 10
ORDER BY 1 DESC