-- 코드를 작성해주세요
SELECT 
    id,
    CASE WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
         WHEN 100 < SIZE_OF_COLONY and SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
         WHEN 1000 < SIZE_OF_COLONY THEN 'HIGH' END as SIZE
FROM ECOLI_DATA
ORDER BY 1 ASC