-- 코드를 입력하세요
SELECT
    b.CATEGORY,
    SUM(s.SALES) as TOTAL_SALES
FROM BOOK_SALES s 
JOIN BOOK b on b.BOOK_ID = s.BOOK_ID
WHERE YEAR(s.SALES_DATE) = 2022 and MONTH(s.SALES_DATE) = 1 
GROUP BY 1
ORDER BY 1